### ISSUE TITLE
just to say hi

### ISSUE THREAD

**Issue by dpnkrpl** [sjaishanker/Benford-Analysis-For-Fraud-Detection#1]
Hi @sjaishanker , I recently came to know about this crazy law (from a Netflix series!). I didn't believe this at the first place, so I planned to test on some real life data. 
What you did in this repo is fantastic. I think we should gather more data from various fields (may be just for fun!) . I still don't believe in this holy cow law 😂😂

**Comment by sjaishanker** [comment]
Hi @deep5050 , thank you for connecting with me. It's so good to know that you went through my repo and I would like to thank you. And yes, definitely we can plan to work more on this, as this new era of data can bring so much information out in the open.

**Comment by dpnkrpl** [comment]
yaay, lets convert this issue to a discussion and talk more there +1
